# Generated by Django 5.2.3 on 2025-10-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
