# Generated by Django 5.2.3 on 2025-11-10 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_empleado_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_generacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
